version: "3"

services:
    surrealdb:
        image: surrealdb/surrealdb:latest
        container_name: surrealdb
        ports:
            - "8000:8000"
        command:
            - start
            - --user=root
            - --pass=root
        restart: always
